name: deploy-prod

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with:
        script_stop: true
        host: sf8do.mooo.com
        username: cm
        port: 22
        key: ${{ secrets.PROD_SSH_KEY }}
        script: |
          cd /home/cm/card-machine-nextjs
          git checkout master
          git pull origin master
          /home/cm/.nvm/nvm-exec npm ci
          /home/cm/.nvm/nvm-exec npm run build
          sudo service card-machine-nextjs restart
